# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  recall-identityapi:
    build:
      context: "E:\\RecALLDemo"
      dockerfile: "Infrastructure/Identity.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RecALLDemo.Infrastructure.Identity.Api.dll"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/RecALLDemo.Infrastructure.Identity.Api.staticwebassets.runtime.CT.json"
    image: "recall-identityapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "E:\\RecALLDemo\\Infrastructure\\Identity.Api:/app:rw"
    working_dir: "/app"
  recall-listapi:
    build:
      context: "E:\\RecALLDemo"
      dockerfile: "Core/List/List.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RecALLDemo.Core.List.Api.dll"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    image: "recall-listapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "E:\\RecALLDemo\\Core\\List\\List.Api:/app:rw"
    working_dir: "/app"
  recall-maskedtextitemapi:
    build:
      context: "E:\\RecALLDemo"
      dockerfile: "Contrib/MaskedTextItem.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RecALLDemo.Contrib.MaskedTextItem.Api.dll"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    image: "recall-maskedtextitemapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "E:\\RecALLDemo\\Contrib\\MaskedTextItem.Api:/app:rw"
    working_dir: "/app"
  recall-servicestatus:
    build:
      context: "E:\\RecALLDemo"
      dockerfile: "Infrastructure/ServiceStatus/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RecALLDemo.Infrastructure.ServiceStatus.dll"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    image: "recall-servicestatus:dev"
    ports: []
    volumes:
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "E:\\RecALLDemo\\Infrastructure\\ServiceStatus:/app:rw"
    working_dir: "/app"
  recall-textitemapi:
    build:
      context: "E:\\RecALLDemo"
      dockerfile: "Contrib/TextItem.Api/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net7.0/RecALLDemo.Contrib.TextItem.Api.dll"
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    image: "recall-textitemapi:dev"
    ports: []
    volumes:
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\ASP.NET\\Https:/root/.aspnet/https"
    - "C:\\Users\\Lenovo\\AppData\\Roaming\\Microsoft\\UserSecrets:/root/.microsoft/usersecrets"
    - "E:\\RecALLDemo\\Contrib\\TextItem.Api:/app:rw"
    working_dir: "/app"
